### ISSUE TITLE
Share state using generate context

### ISSUE THREAD

**Issue by allevo** [trezm/Thruster#100]
Hi!
I would like to share a state between requests storing it into request context.

The proposal is to create a new trait that implements a method `generate` 

```
pub trait ContextGenerator {
    fn generate(req: R) -> T;
}
```

The change is about 

- create a new constructor
- create a basic implementation of ContextGenerator in order to support the older constructor
- https://github.com/trezm/Thruster/blob/9ddae50167e3332fdea23bedfc1a36fff579b5a2/src/app.rs#L87

- https://github.com/trezm/Thruster/blob/9ddae50167e3332fdea23bedfc1a36fff579b5a2/src/app.rs#L103

- https://github.com/trezm/Thruster/blob/9ddae50167e3332fdea23bedfc1a36fff579b5a2/src/app.rs#L196

**Comment by trezm** [comment]
I think this is a great suggestion. In order to maintain backcompat, perhaps it makes sense to alter this method:

https://github.com/trezm/Thruster/blob/master/src/app.rs#L100

And create a new one along side along the lines of

```rust
  pub fn build(generator: ContextGenerator<R, T>) -> App<R, T> {
    App {
      _route_parser: RouteParser::new(),
      context_generator: generator // Note that internally we can update this to be a ContextGenerator
    }
  }
```

**Comment by trezm** [comment]
All set!
