### ISSUE TITLE
Tokio has fallen

### ISSUE THREAD

**Issue by CKarper** [trezm/Thruster#109]
RE: https://github.com/tokio-rs/tokio/issues/1087#issuecomment-491901368

For the time being, for `await` support, you must use github to depend on tokio.

```sh
    Checking tokio-async-await v0.1.7
error[E0432]: unresolved import `std::await`
  --> /Users/ckarper/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-async-await-0.1.7/src/lib.rs:35:9
   |
35 | pub use std::await as std_await;
   |         ^^^^^^^^^^^^^^^^^^^^^^^ no `await` in the root

```

**Comment by trezm** [comment]
Was thinking of this in the car this morning, had to do this when I was first adopting async as well. Mildly annoying, will put up a fix tomorrow and a minor version bump.
