### ISSUE TITLE
Accept tokio handle instead of spinning up your own event loop

### ISSUE THREAD

**Issue by nihiluis** [trezm/Thruster#11]
I only checked the examples for the feature, maybe it does already exist (?).

It's useful if you want to have multiple tokio servers in your application, but only one (tokio) event loop.

It's also discussed here (more elaborately):

https://github.com/gotham-rs/gotham/issues/95

**Comment by trezm** [comment]
According to [this](https://github.com/tokio-rs/tokio-proto/issues/110), it looks like this feature is upcoming in Tokio!

Right now we rely on their `TcpServer` module, that being said, I do believe (and this is likely related to your issue #12,) that we could use their `with_handle` to grab a core to do work on if you wanted to, say, spawn a hyper request.

**Comment by nihiluis** [comment]
Yep. With the upcoming tokio reform there will possibly also be major changes for tokio proto.

https://github.com/tokio-rs/tokio/issues/118

**Comment by trezm** [comment]
Closing this as we're now using the tokio handle that's accessible via their default core methods.
