### ISSUE TITLE
Route parameters with async await?

### ISSUE THREAD

**Issue by xacrimon** [trezm/Thruster#116]
Currently when i try to use route parameters i get a panic with the message `Chain out of cycle` from the thruster-core-async-await crate L39.

**Comment by trezm** [comment]
Yikes! Can you provide a code sample to replicate the issue? Usually that happens when `next` is called but there isn't any more middleware to `next` to.

**Comment by xacrimon** [comment]
Sure i can! Happy you could respond so quickly. The offending code is here `https://gitlab.nebulanet.cc/xacrimon/meme-api`. Its very small. The problem happens with the routing and execution of the h_v2_random handler. When i specify a parameter it works without issues but if i omit the parameter it panics while i would expect it to not match the route.

**Comment by trezm** [comment]
Anything for dank memes!

Im on my phone right now, but will be able to get a closer look tomorrow
when I'm near a computer.

**Comment by xacrimon** [comment]
Alright. Do so. I do have a suspicion it is due to the route matching erroneously without queueing the middleware. Thus it causing an out-of-chain.
