### ISSUE TITLE
Serving of moderate size assets > 1MiB super slow

### ISSUE THREAD

**Issue by xacrimon** [trezm/Thruster#118]
As the title says responses with significant size take a lot of time such that i can't get more than 300 requests per second for a 1MiB image that is cached in ram.

**Comment by trezm** [comment]
I'll take a look into this!

**Comment by trezm** [comment]
Are you able to provide some sample code as well?

**Comment by xacrimon** [comment]
Of course! The service which had this problem has since been rewritten using actix-web until async await drops. Thanks to git history however it is still available here https://gitlab.nebulanet.cc/xacrimon/dubu-api/tree/28169c09171f9136d48374e2f07ae5769f72d276

**Comment by trezm** [comment]
After looking into this at a surface level, it seems like responses are scaling proportionately with the size of the payload (plus a constant,) what are you expecting/comparing these stats to? If another framework (actix I imagine,) is providing consistently better results, I can check into what they're doing differently!

**Comment by xacrimon** [comment]
I'd imagine this is because of the underlying HTTP impl. Yes I am comparing
it to actix and hyper.

**Comment by xacrimon** [comment]
Probably due to how responses are actually being sent. Maybe streaming or something of the like.

**Comment by trezm** [comment]
That was my initial assumption as well, as the basic server implementation uses a framed response. Using hyper as an underlying mechanism is also an option, let me see if that tweaks the performance a significant amount.

**Comment by xacrimon** [comment]
Sounds good!

**Comment by trezm** [comment]
Alrighty, there's still some more long term work to do, but I got about a 20% speedup for the time being! Check out #119 for more details

**Comment by xacrimon** [comment]
Did using hyper as a server speed it up? @trezm

**Comment by trezm** [comment]
Ah, good question. I'm actually having some trouble integrating hyper with the new async await. Lots of complaints around how `hyper::body::Body` can't be sent between threads.

**Comment by xacrimon** [comment]
Ah, same issues here. Was going to report it. Nothing in hyper is
compatible here. Just with this frameworks. No problem with others. Hyper
client doesn't work either.

**Comment by trezm** [comment]
Hmm, that's interesting. I've had success using `reqwest` which is based on hyper using Thruster.

As for the Body, I'm sure there's a way to do it, the backend is just in a state of flux since it supports both legacy and nightly futures/async-await.

**Comment by xacrimon** [comment]
Reqwests sync works. It's async that causes issues.

**Comment by trezm** [comment]
Just checking in, definitely making some headway. Hopefully will have a working hyper/async combo in the next couple of days.

The issue, for posterity, is that we're storing the request stream on the Context. This requires that the stream be `Sync` so that the work can be shared. If I disable storing the `request` on the Context, it actually compiles fine (although it obviously isn't very useful since we don't have any  data to read from.

I'll keep poking at it and see if I can find a workaround.

**Comment by trezm** [comment]
Alright, found the solution, merged in as of #119. You should now be able to use hyper on the backend, with pretty good results too! About 94% of the throughput of the Actix version, and that's with very little tweaking.

Also, you should now be able to use hyper as an http client if you need to make external requests.

**Comment by xacrimon** [comment]
Yay! Sounds good.
