### ISSUE TITLE
Actually use the request method in thruster_testing::request

### ISSUE THREAD

**Issue by cquintana-verbio** [trezm/Thruster#126]
The `request` method is the generic version for the `thruster_testing` request methods, and is the only way to pass headers when writing tests.

However, despite allowing the developer to write the method as a String, it only allows testing GET methods, as the route resolver does not use the `method` param:

https://github.com/trezm/Thruster/blob/master/thruster-app/src/testing.rs#L26

**Comment by trezm** [comment]
🤦‍♀️yes, you are absolutely right! Clearly a dumb mistake by me. I'll be able to fix this in the next few days, or feel free to put up a PR if you beat me to it!
