### ISSUE TITLE
Running `cargo test` on Thruster's repository results in several errors

### ISSUE THREAD

**Issue by agersant** [trezm/Thruster#140]
Getting many errors, compiling with latest stable:

![image](https://user-images.githubusercontent.com/817256/72661170-0dec0e00-398c-11ea-97dc-29221b79eab4.png)

**Comment by trezm** [comment]
Ah yep, I knew there would be a place I forgot to fully migrate when futures stabilized. I'm on it! Thanks for the heads up!

**Comment by trezm** [comment]
This should now be fixed
