### ISSUE TITLE
[Question] Group routes

### ISSUE THREAD

**Issue by theredfish** [trezm/Thruster#29]
Hi there,

I'm trying Thruster (good job !) and I would like to group my routes with the same base path. Example :

- `/admin`
- `/admin/:adminId/posts`

Middlewares (with a naive approach) :
- `_app.get("/admin", vec![show_admins]);`
- `_app.get("/admin/:adminId/posts", vec![show_admin_posts]);`

How do you associate a different middleware for `/admin/:adminId/posts`? Currently, this route match the middleware of `/admin/` first (which returns a json response for example).

thank you!

**Comment by theredfish** [comment]
Hello @trezm :),
thank you for the very detailed answer, I will try to follow your instructions asap :+1: 

See you on gitter!

**Comment by trezm** [comment]
Great! Closing this issue then :)
