### ISSUE TITLE
raw_body should not return an &str

### ISSUE THREAD

**Issue by aidanhs** [trezm/Thruster#39]
https://docs.rs/thruster/0.4.4/thruster/struct.Request.html#method.raw_body

It seems odd that thruster does extra work in this method when it's actually holding the body as a bunch of bytes internally.

**Comment by trezm** [comment]
Are you thinking an `&[u8]` and let the caller do what they will with it? I'd get on board with that.

**Comment by aidanhs** [comment]
Yep exactly. Otherwise you can't post binary files, like images.

**Comment by trezm** [comment]
Resolved by #54
