### ISSUE TITLE
Consider offloading types to the HTTP crate

### ISSUE THREAD

**Issue by whitfin** [trezm/Thruster#41]
I'm curious if you've thought about moving some of your types to the [http](https://crates.io/crates/http) crate. This would reduce the amount of code you're having to maintain, and also be more familiar to people coming from other frameworks (Hyper, etc). 

No bother if you can't/don't want to, just thought it might be worth a suggestion! The reason I bring it up now is that it'd be easier now than later to migrate :p

**Comment by trezm** [comment]
Definitely a good thought! I was just playing around a little bit with seeing about migrating over and ran into some problems with the request. We attach a lot of data on to the request, esp. route params and query params.

That's not to say this isn't doable, and I would like to have both `Response` and `Request` to match (both custom, or both the `http` lib.) I think it's not on my short list for now though!

(If anyone else picks up this thread, here are the lines I was thinking of: [query params](https://github.com/trezm/Thruster/blob/master/src/route_parser.rs#L49-L50) and [route params](https://github.com/trezm/Thruster/blob/master/src/route_tree/node.rs#L150)

Closing for now!
