### ISSUE TITLE
Add a wildcard route that matches all routes

### ISSUE THREAD

**Issue by theredfish** [trezm/Thruster#44]
Hello,

Currently `set404` function allows to set the middleware if no route is successfully matched . This function can be renamed to be less specific, since it's the developer who defines the logic.

My proposition : 

- Define all routes with a specific match
- Define a default behavior for routes that do not match : forward, 404, 403, ... 

We can rename `set404` with something like `set_default_behavior` / `set_default_middleware`... or with the name you want, the discussion is opened :)

**Comment by trezm** [comment]
Many of the other frameworks handle this by simply allowing the definition of a `*` route. That will handle anything that's not already caught. The way our tree is laid out that's another idea -- i.e. remove the set404 entirely and leave it up to the developer to define a wildcard route.

**Comment by theredfish** [comment]
Hello,
Just a little update : I found a way to push an agnostic middleware to wildcard nodes, but I'm experiencing some issues with routes having a parameter :)

I will push my first commit on my fork at the end of the day.

**Comment by trezm** [comment]
This is potentially closed by #52, try it out on master and let me know! It's published as `thruster = "0.5.0-beta10"`
