### ISSUE TITLE
[Question] Server shutdown

### ISSUE THREAD

**Issue by hscasn** [trezm/Thruster#46]
I'm new to Rust and Thruster, coming from a Node.js background. I would like to know if there is a way to gracefully shut down a Thruster server and do some cleanup before the process ends.

In Node, I can listen for a SIGTERM and prepare for the shutdown like this:

```
process.on('SIGTERM', () => {
    log.warn('SIGTERM received. Stopping server.');
    myServices.stopAll();
    server.close();
});
```

Is there a way to do something similar with Thruster?

Thanks!

**Comment by trezm** [comment]
Thruster currently uses the tokio runtime, so I believe you should be able to call something along the lines of this: https://docs.rs/tokio/0.1/tokio/runtime/struct.Runtime.html#method.shutdown_now, and it'll shutdown the whole thing. In terms of SIGTERM, you'd have to listen for that event, but it looks like you might have to drop down into unsafe/unstable land with libc :( https://doc.rust-lang.org/1.7.0/libc/

**Comment by hscasn** [comment]
Thanks a lot!
