### ISSUE TITLE
Provide a default context method in the library to simplify hello world

### ISSUE THREAD

**Issue by funkjunky** [trezm/Thruster#50]
The generate_context method is very simple and useful as a baseline. I think it'd be convenient if it was exported by the library its self.

**Comment by trezm** [comment]
That's a good point, although I don't want to openly encourage the use of `BasicContext`, as I feel it's, well, basic! That being said, if we're providing a `BasicContext` then we might as well provide a default method to generate one.

**Comment by trezm** [comment]
Closed by #61
