### ISSUE TITLE
Run and fix Clippy issues

### ISSUE THREAD

**Issue by trezm** [trezm/Thruster#59]
We should be using best practices in this repository. So:
- Add clippy to our Travis build
- Fix clippy issues locally

**Comment by theredfish** [comment]
I would like to take this issue. Nobody started to work on it?

**Comment by trezm** [comment]
Not yet! Go for it!

**Comment by theredfish** [comment]
Should we fail the build if there are warnings?

**Comment by trezm** [comment]
Yup, great idea!!
