### ISSUE TITLE
F5

### ISSUE THREAD

**Issue by ami44** [trezm/Thruster#67]
Hello

- ``rustc --version`` -> ``rustc 1.28.0 (9634041f0 2018-07-30)``
- ``cargo run --example most_basic``
- open ``http://127.0.0.1:4321/plaintext``
- "Hello, World !" - Firefox or Chrome - :-)
- F5 .... "lost connection/ERR_EMPTY_RESPONSE" - Firefox or Chrome -  :-(

Ami44

**Comment by trezm** [comment]
Very strange... I'm seeing the same thing: 
- First time the page is visited it loads correctly
- Second time it gets `ERR_EMPTY_RESPONSE`

**Comment by ami44** [comment]
Thank
