### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ami44** [trezm/Thruster#68]
Windows 

- ``cargo run --example most_basic``-> - ``error[E0432]: unresolved import `net2::unix```

Thruster is only Linux ?

Ami44

**Comment by trezm** [comment]
I'll have to get a VM to test this one, but that shouldn't be the case.

**Comment by ami44** [comment]
ok, but not "urgent"

**Comment by ami44** [comment]
i confirm, it's ok
thanks
ami44
