### ISSUE TITLE
too basic context

### ISSUE THREAD

**Issue by ami44** [trezm/Thruster#70]
As a new user, I find it constraining to code (each time) my own "context.rs" to start a new project. it's not intuitive.

Some basic methods in BasicContext should be proposed by default which allow to define headers (add, del) and define the return code (404)

- add_header("headerKey", "value")
- set_status_code(418)

Thanks
Ami44

**Comment by trezm** [comment]
I agree. I think, in general, `BasicContext` should provide a relatively generic but capable experience for those getting started. As such, I believe the methods should be:

```rust
fn set_header(key: &str, val: &str)
fn remove_header(key: &str)
fn set_status_code(code: u32, message: &str)
```

**Comment by ami44** [comment]
why not

koa or express methods

- res.set(field, value) [koa](https://github.com/koajs/koa/blob/master/docs/api/response.md#responsesetfield-value) or [express](http://expressjs.com/fr/api.html#res.set)
- res.append(field , value) [koa](https://github.com/koajs/koa/blob/master/docs/api/response.md#responseappendfield-value) or [express](http://expressjs.com/fr/api.html#res.append)
- res.remove(field) [koa](https://github.com/koajs/koa/blob/master/docs/api/response.md#responseremovefield) - not found express

beware

res.status(code) [koa](https://github.com/koajs/koa/blob/master/docs/api/response.md#responsestatus) or [express](http://expressjs.com/fr/api.html#res.status) - is not necessary to pass second string params

ami44

**Comment by trezm** [comment]
I have a few questions;
- What is the functional difference for the developer between `set` and
`append`?
- Is there a reason to exactly align with koa and express on names? I find
that a slightly more detailed name is very informative, especially as the
context object becomes large.
- There's actually a builtin struct where we could build out more status
codes (right now it only has ok and custom,) do you think that's easier
than passing a blank string? Personally, I dislike having to `use` in an
extra enum, but requiring the existing enum is likely more ergonomic to
Rust.

**Comment by ami44** [comment]
Q1: Is there a reason to exactly align with koa and express on names?
R1: for reasons of consistency "Based on frameworks like Koa, and Express" at front page https://github.com/trezm/Thruster#intuitive
and for marketing reasons: to attract more koa or express developers to thruster because they will quickly find the same methods (et get more stars than actix-web :-))

Q2: What is the functional difference for the developer between `set` and `append`?
R2: I think "set" should overwrite the previous value if key exists, otherwise call append

Q3: do you think that's easier than passing a blank string
R3: no idea! see my response R1

Ami44

**Comment by trezm** [comment]
Hmm, valid points all around. I guess since this isn't like it lives in the
trait, it would be worth going through the koa and/or express libraries and
just copying over a bunch of methods to the BasicContext.

For set vs. append, I think we'll only support set for simplicity's sake.
My guess is that `append` will actually create a comma separated list of
values in Koa or Express, but we can leave that for a later exercise :).
I'll mark this as an improvement for dev!
