### ISSUE TITLE
thruster template

### ISSUE THREAD

**Issue by ami44** [trezm/Thruster#79]
I have created a little thruster template: https://github.com/ami44/thruster-basic-template with tests, coverage and livereload.

Can you test if is ok, and fork if you need

I'm going to be out of town from now on. I hope to integrate evolutions when you have solved other problems (but without guarantee). 

Ami44

**Comment by trezm** [comment]
Absolutely incredible! I think that's an incredible starting point for new developers -- I'll mark this as a chore so I remember to add it to the readme. Thank you so much for this incredible contribution!
