### ISSUE TITLE
README mistake

### ISSUE THREAD

**Issue by ddibiase** [trezm/Thruster#96]
In the basic example of the README the endpoint declaration is currently:

    app.get("/plaintext", middleware![plaintext]);

But the correct way seems to be:

    app.get("/plaintext", middleware![Ctx => plaintext]);

Might want to adjust it, through me off at first might do the same to others.

**Comment by trezm** [comment]
Ah, you're absolutely right!!! Thank you so much for pointing that out!
I'll get on the fix tonight when I'm near a computer
